Updating npsupport.py to fail gracefully without numpy
Adding the check for numpy in isdatetime64 so that it doesn't fail when numpy is not present, which can cause comtypes.automation.tagVARIANT._set_value to except when called with certain datatypes:
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types